name: List Directory Contents On Demand

on:
  workflow_dispatch:

env:
  PRPC_PLATFORM_DIR: /home/barar/work/code/prpc-platform

jobs:
  list-directory:
    runs-on: self-hosted
    steps:
      - name: List contents of the root directory
        run: ls -la "$PRPC_PLATFORM_DIR"
  Checkout-code:
    runs-on: self-hosted
    steps:
      - name: Checkout to master
        run: cd "$PRPC_PLATFORM_DIR" && git branch && git checkout master && git branch
